config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"} 
  resources :units
  resources :users
  resources :places
  resources :types

  root to: 'search#index'
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def to_s
    name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :x_people, :image, :unit_id)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :x_people %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<div class="givepaddings">
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>
</div>

app/views/types/index.html.erb
<div class="givepaddings">
<h1>Listing types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>X people</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.x_people %></td>
        <td><%= type.image %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>
</div>

app/views/types/new.html.erb
<div class="givepaddings">
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>
</div>

app/views/types/show.html.erb
<div class="givepaddings">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>X people:</strong>
  <%= @type.x_people %>
</p>

<p>
  <strong>Image:</strong>
  <%= @type.image %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>
</div>