config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"} 
  resources :units
  resources :users
  resources :places
  resources :types

  root to: 'search#index'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :place
  belongs_to :type

  accepts_nested_attributes_for :place
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]


  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
    @types = Place.all.map {|type| [type.name, type.id]}
    @places = Place.all.map {|place| [place.name, place.id]}
  end

  # GET /units/1/edit
  def edit
    @types = Type.all.map {|type| [type.name, type.id]}
    @places = Place.all.map {|place| [place.name, place.id]}
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:amount, :type_id, :place_id)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :amount %>
  <%= f.label :place_id %><br />
  <%= f.select :place_id, @places %><br />
  <%= f.label :type_id %><br />
  <%= f.select :type_id, @types %><br /><br />
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                units_path, :class => 'btn' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="givepaddings">
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="givepaddings">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Type</th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.id, unit_path(unit) %></td>
        <td>
        <%= unit.type.name if unit.type %>
            
        <% #end %>
        </td>
        <td><%= unit.amount %></td>
        <td>
          <%= unit.place.name if unit.place %>
        </td>
        <td><%=l unit.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_path,
            :class => 'btn btn-primary' %>
</div>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="givepaddings">
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="givepaddings">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:place_id) %>:</strong></dt>
  <dd><%= @unit.place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_id) %>:</strong></dt>
  <dd><%= @unit.type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @unit.amount %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>